import React from 'react'
import { Routes, Route } from 'react-router-dom'

import Navbar from './components/Navbar.jsx'

import Home from './pages/Home.jsx'
import ScanQR from './pages/ScanQR.jsx'
import UploadQR from './pages/UploadQR.jsx'
import PasteURL from './pages/PasteURL.jsx'
import Dashboard from './pages/Dashboard.jsx'
import History from './pages/History.jsx'
import About from './pages/About.jsx'
import Contact from './pages/Contact.jsx'

import AuthorityLogin from './pages/AuthorityLogin.jsx'
import AuthorityDashboard from './pages/AuthorityDashboard.jsx'

export default function App() {
  return (
    <div className="app-shell">

      <Navbar />

      <Routes>

        {/* Public pages */}
        <Route path="/" element={<Home />} />
        <Route path="/scan" element={<ScanQR />} />
        <Route path="/upload" element={<UploadQR />} />
        <Route path="/paste" element={<PasteURL />} />
        <Route path="/about" element={<About />} />
        <Route path="/contact" element={<Contact />} />

        {/* Authority pages */}
        <Route
          path="/authority-login"
          element={<AuthorityLogin />}
        />

        <Route
          path="/authority"
          element={<AuthorityDashboard />}
        />

        {/* Existing pages - we'll protect these later */}
        <Route path="/dashboard" element={<Dashboard />} />
        <Route path="/history" element={<History />} />

      </Routes>

      <footer className="footer">
        QRShield AI — a B.Tech AIML academic project. Predictions are generated by a
        machine learning model trained on a phishing-URL feature dataset; they are
        probabilistic estimates, not a guarantee of safety.
      </footer>

    </div>
  )
}

